name: Release
on:
  # Dispatched by tagpr workflow.
  workflow_dispatch:

inputs:
  platform:
    default: linux/arm64
    required: false
    description: The target build platform
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        push: true
        build-args:
          TARGETARCH=linux/arm64
        tags: ghcr.io/${{ github.repository }}:arm64-${{ github.ref_name }}
